# Generated by Django 5.2.9 on 2026-01-21 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.stream')),
            ],
        ),
    ]
