# Generated by Django 5.2.9 on 2026-01-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='sub_name',
            new_name='name',
        ),
    ]
