# Generated by Django 5.2.8 on 2026-02-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_alter_stream_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
